
package com.jaxws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScoreServiceImplService", targetNamespace = "http://jaxws.com/", wsdlLocation = "http://localhost:9999/scoreService?wsdl")
public class ScoreServiceImplService
    extends Service
{

    private final static URL SCORESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCORESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SCORESERVICEIMPLSERVICE_QNAME = new QName("http://jaxws.com/", "ScoreServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/scoreService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCORESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SCORESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ScoreServiceImplService() {
        super(__getWsdlLocation(), SCORESERVICEIMPLSERVICE_QNAME);
    }

    public ScoreServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCORESERVICEIMPLSERVICE_QNAME, features);
    }

    public ScoreServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SCORESERVICEIMPLSERVICE_QNAME);
    }

    public ScoreServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCORESERVICEIMPLSERVICE_QNAME, features);
    }

    public ScoreServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoreServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScoreServiceImpl
     */
    @WebEndpoint(name = "ScoreServiceImplPort")
    public ScoreServiceImpl getScoreServiceImplPort() {
        return super.getPort(new QName("http://jaxws.com/", "ScoreServiceImplPort"), ScoreServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScoreServiceImpl
     */
    @WebEndpoint(name = "ScoreServiceImplPort")
    public ScoreServiceImpl getScoreServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.com/", "ScoreServiceImplPort"), ScoreServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCORESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SCORESERVICEIMPLSERVICE_EXCEPTION;
        }
        return SCORESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
